#!/bin/sh

set -e -o pipefail

gitlab_api_request()
{
  curl -fsX $1 --header "PRIVATE-TOKEN: $PRIVATE_TOKEN" "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/$2"
}

REVIEW_APP_IDS=$(gitlab_api_request "GET" "environments" | jq -c '.[] | select(.name | startswith("review/")) | .id')

for REVIEW_APP_ID in $REVIEW_APP_IDS; do
  gitlab_api_request "POST" "environments/$REVIEW_APP_ID/stop" > /dev/null
done
